---
apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    app: reviews
    service: reviews
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  labels:
    app: reviews
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
      - name: reviews
        image: codingcorp-docker.pkg.coding.net/nocalhost/bookinfo/reviews
        env:
        - name: server.port
          value: "9080"
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
          failureThreshold: 1
          periodSeconds: 10
